font_family                   GeistMono Nerd Font

font_size                     13

bold_font                     auto

italic_font                   auto

bold_italic_font              auto

background_opacity            0.60

dynamic_background_opacity    yes

window_padding_width          8

confirm_os_window_close       0

draw_minimal_borders          yes

window_border_width           0